export default {
  HOME: ["POPULAR_MOVIES", "POPULAR_SERIES", "TRENDING_ALL"],
  MOVIES: ["POPULAR_MOVIES", "TRENDING_MOVIES", "RATED_MOVIES"],
  SERIES: ["POPULAR_SERIES", "TRENDING_SERIES", "RATED_SERIES"],
  DETAILS: ["RECOMENDED"],
};
