export default {
  HOME: ["POPULAR_MOVIES", "POPULAR_SERIES", "TRENDING_ALL"],
  MOVIES: ["POPULAR_MOVIES", "RATED_MOVIES", "TRENDING_MOVIES"],
  SERIES: ["POPULAR_SERIES", "RATED_SERIES", "TRENDING_SERIES"],
  INFOPAGE: ["RECOMENDED_SERIES"],
};
